# Generated by Django 3.2 on 2021-07-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Makole', '0003_auto_20210714_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='makolebatch',
            name='quantity_received',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
