# Generated by Django 3.2 on 2021-07-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Makole', '0005_makolebatch_concentration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makolebatch',
            name='unit_of_measure',
            field=models.CharField(blank=True, choices=[('ml', 'ML'), ('cp', 'CP'), ('tb', 'TB')], default='tb', max_length=10),
        ),
    ]
