# Generated by Django 3.2 on 2021-08-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Makole', '0008_makolebatch_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makolebatch',
            name='used',
            field=models.IntegerField(default=0),
        ),
    ]
