# Generated by Django 3.2 on 2021-08-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Makole', '0009_alter_makolebatch_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makolebatch',
            name='batch_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
