# Generated by Django 3.2 on 2021-08-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Makole', '0010_alter_makolebatch_batch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makolebatch',
            name='used',
            field=models.FloatField(default=0),
        ),
    ]
