# Generated by Django 3.2 on 2021-06-26 07:55

import MSD.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DTS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, default=MSD.models.Medicine.generate_num, editable=False, max_length=10, unique=True)),
                ('quantity', models.IntegerField()),
                ('used', models.IntegerField(blank=True, default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('stock_status', models.CharField(blank=True, max_length=30, null=True)),
                ('on_route', models.BooleanField(blank=True, default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DTS.batch')),
            ],
        ),
    ]
