# Generated by Django 3.2 on 2021-06-29 18:40

import MSD.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DTS', '0001_initial'),
        ('MSD', '0002_auto_20210628_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_type',
        ),
        migrations.RemoveField(
            model_name='ordereditem',
            name='medicine',
        ),
        migrations.AddField(
            model_name='order',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DTS.institute'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DTS.batch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='reference_number',
            field=models.IntegerField(blank=True, default=MSD.models.Order.generate_num, editable=False, unique=True),
        ),
        migrations.DeleteModel(
            name='OrderType',
        ),
    ]
