# Generated by Django 3.2 on 2021-06-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSD', '0004_auto_20210629_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='item_number',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, default='inc', max_length=3),
        ),
    ]
