# Generated by Django 3.2 on 2021-06-29 21:46

import MSD.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MSD', '0005_auto_20210630_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='item_number',
            field=models.IntegerField(blank=True, default=MSD.models.OrderedItem.generate_num, unique=True),
        ),
    ]
