# Generated by Django 3.2 on 2021-07-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Benja', '0005_auto_20210714_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='benjabatch',
            name='concentration',
            field=models.CharField(default='200mg', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='benjabatch',
            name='quantity_received',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='benjabatch',
            name='unit_of_measure',
            field=models.CharField(blank=True, default='tablet', max_length=10),
        ),
    ]
