# Generated by Django 3.2 on 2021-08-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Benja', '0006_auto_20210714_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='benjabatch',
            name='used',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
