# Generated by Django 3.2 on 2021-06-30 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DTS', '0001_initial'),
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Batch',
            new_name='HospitalBatch',
        ),
        migrations.RenameModel(
            old_name='Medicine',
            new_name='HospitalMedicine',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_number',
            new_name='patient',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Hospital.userprofile'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('is_sold', models.BooleanField(blank=True, default=False)),
                ('sid', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.appointment')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DTS.batch')),
            ],
        ),
    ]
