# Generated by Django 3.2 on 2021-08-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0006_hospitalbatch_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalbatch',
            name='used',
            field=models.IntegerField(default=0),
        ),
    ]
