# Generated by Django 3.2 on 2021-06-09 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DTS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DTS.userprofile'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
