# Generated by Django 3.2 on 2021-07-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTS', '0002_transaction_corresponding_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='corresponding_transaction',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
