# Generated by Django 3.2 on 2021-06-09 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DTS', '0002_auto_20210609_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='approval',
        ),
        migrations.AlterField(
            model_name='approval',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DTS.batch'),
        ),
    ]
