# Generated by Django 3.2 on 2021-07-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTS', '0003_alter_transaction_corresponding_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='initiator',
            field=models.CharField(default='Michael G', max_length=50),
            preserve_default=False,
        ),
    ]
