# Generated by Django 3.2 on 2021-06-14 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DTS', '0003_auto_20210609_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='approval',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DTS.approval'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
