# Generated by Django 3.2 on 2021-07-14 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DTS', '0004_transaction_initiator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DTS.userprofile'),
        ),
    ]
