# Generated by Django 3.2 on 2021-06-14 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DTS', '0004_auto_20210614_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='approval',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='DTS.approval'),
        ),
    ]
