# Generated by Django 3.2 on 2021-06-14 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DTS', '0006_auto_20210614_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approval',
            name='approver',
        ),
    ]
