# Generated by Django 3.2 on 2021-06-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTS', '0007_remove_approval_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='is_rejected',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
