# Generated by Django 3.2 on 2021-08-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTS', '0007_batch_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='used',
            field=models.IntegerField(default=0),
        ),
    ]
