# Generated by Django 3.2 on 2021-06-14 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DTS', '0008_approval_is_rejected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approval',
            old_name='is_rejected',
            new_name='is_declined',
        ),
    ]
