# Generated by Django 3.2 on 2021-06-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTS', '0009_rename_is_rejected_approval_is_declined'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='quantity_received',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
