# Generated by Django 3.2 on 2021-08-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTS', '0009_auto_20210812_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
