# Generated by Django 3.2 on 2021-08-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTS', '0010_manufacturer_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
