# Generated by Django 3.2 on 2021-08-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTS', '0011_alter_manufacturer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.IntegerField(max_length=20, unique=True),
        ),
    ]
