# Generated by Django 3.2 on 2021-06-23 18:15

import DTS.transaction_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTS', '0011_remove_transaction_quantity_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference_number',
            field=models.CharField(blank=True, default=DTS.transaction_models.Transaction.generate_num, editable=False, max_length=20, unique=True),
        ),
    ]
