# Generated by Django 3.2 on 2021-08-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTS', '0012_alter_batch_batch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
