# Generated by Django 3.2 on 2021-08-23 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DTS', '0013_alter_batch_batch_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugTrackTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_destroyed', models.IntegerField()),
                ('destroyer', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('destroyed', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='DTS.expiredtable')),
            ],
        ),
    ]
