# Generated by Django 3.2 on 2021-08-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DTS', '0014_drugtracktable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expiredtable',
            name='date_added',
        ),
        migrations.AlterField(
            model_name='expiredtable',
            name='destruction_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
